AWSTemplateFormatVersion: '2010-09-09'
Description: External, public facing load balancer, for forwarding public traffic to containers
Parameters:
  ProjectName:
    Type: String
    Default: api-boilerplate

  VpcId:
    Type: String
    Description: VPC From network stack
  
Resources:
  SecurityGroupToPublicLoadBalancer:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # GroupName: !Sub ${ProjectName}-sg-public-load-balancer
      GroupDescription: Access to the public facing load balancer
      VpcId: !Sub ${VpcId}
      SecurityGroupIngress:
          - CidrIp: 0.0.0.0/0 # allow every access from anywhere
            IpProtocol: tcp
            FromPort: 80
            ToPort: 80

      SecurityGroupEgress:
          - CidrIp: 0.0.0.0/0 
            IpProtocol: -1  # -1 means all protocols 
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-sg-public-load-balancer

  PublicApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: '30'
      Subnets:
        - Fn::ImportValue: !Sub ${ProjectName}:PublicSubnetOne
        - Fn::ImportValue: !Sub ${ProjectName}:PublicSubnetTwo
      SecurityGroups: [!Ref 'SecurityGroupToPublicLoadBalancer']
      Name: !Sub ${ProjectName}-public-alb-ecs
  
  TargetGroupFargateService:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: /health-check
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      TargetType: ip # network mode aws-vpc
      UnhealthyThresholdCount: 2
      Name: !Sub ${ProjectName}-tg-fargate
      VpcId: !Sub ${VpcId}

  PublicLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - PublicApplicationLoadBalancer
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref 'TargetGroupFargateService'
      LoadBalancerArn: !Ref 'PublicApplicationLoadBalancer'
      Port: 80
      Protocol: HTTP

Outputs:
  ExternalUrl:
    Description: The url of the external load balancer
    Value: !Sub http://${PublicApplicationLoadBalancer.DNSName}
    Export:
      Name: !Sub ${ProjectName}:ExternalUrl